#.travis.yml
sudo: required
dist: trusty
language: node_js
before_install:
  - npm install -g truffle ganache-cli npm@^6.0.0
cache:
  directories:
  - "$HOME/.npm"
install:
  - npm ci --production=false
matrix:
  include:
  - if: branch =~ /^(master$|release\/)/ OR tag IS present
    env: NODE_ENV=production
    node_js: '9'
  - if: branch =~ /^(master$|release\/)/ OR tag IS present
    env: NODE_ENV=production
    node_js: '8'
  - if: NOT (branch =~ /^(master$|release\/)/)
    env: NODE_ENV=development
    node_js: '9'
  - if: NOT (branch =~ /^(master$|release\/)/)
    env: NODE_ENV=development
    node_js: '8'
deploy:
  - provider: s3
    bucket: $DEV_BUCKET_NAME
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    local_dir: dist
    on:
      branch: develop
      node: '9'
  - provider: s3
    bucket: $STAGING_BUCKET_NAME
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    local_dir: dist
    upload-dir: current
    on:
      branch: master
      node: '9'
  - provider: s3
    bucket: $STAGING_BUCKET_NAME
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    local_dir: dist
    upload-dir: releases/$TRAVIS_TAG
    on:
      tags: true
      node: '9'
